version: '3'
services:
  app:
    build: .
    environment:
      BOILERPLATE_ENV: "prod"
      DATABASE_URL: "mysql+mysqldb://root:root@db:3306/cybuildings"
    links:
    - db
    ports:
    - "5000:5000"

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3311:3306"
    volumes:
      - data2:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: "mydb"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
      TZ: "Asia/Shanghai"
#      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  data2:
    driver: local

