version: '3'
services:
  app:
    build: .
#    command: "gunicorn manage:app -w 8 -b 0.0.0.0:5000 -k gevent"
    command: "supervisord -n"
    environment:
      BOILERPLATE_ENV: "prod"
      DATABASE_URL: "mysql+mysqldb://root:root@db:3306/mydb"
    links:
      - db
      - celery
      - redis
    networks:
      - mynet
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3311:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d/
    networks:
      - mynet
    environment:
      MYSQL_DATABASE: "mydb"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
      TZ: "Asia/Shanghai"
#      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  celery:
    build: .
    command: "celery worker -A app.main.celery --loglevel=info -b redis://redis:6379/0 "
    user: nobody
    environment:
      BOILERPLATE_ENV: "prod"
      DATABASE_URL: "mysql+mysqldb://root:root@db:3306/mydb"
    links:
      - redis
    networks:
      - mynet

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - mynet

networks:
  mynet:


